# Generated by Django 3.0.4 on 2020-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='slug',
            field=models.SlugField(default='aaa', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assettype',
            name='allowed_for',
            field=models.ManyToManyField(blank=True, related_name='allowed_asset_types', related_query_name='allowed_asset_types', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='required_for',
            field=models.ManyToManyField(blank=True, related_name='required_asset_types', related_query_name='required_asset_types', to='contenttypes.ContentType'),
        ),
    ]
