# Generated by Django 3.2.8 on 2021-10-21 11:24

import bitfield.models
from django.db import migrations, models
import image_assets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image_assets', '0008_auto_20200528_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='min_duration',
            field=models.IntegerField(default=0, verbose_name='Min Duration'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.FileField(upload_to='', validators=[image_assets.validators.AssetValidator()], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='formats',
            field=bitfield.models.BitField((('jpeg', 'JPEG'), ('png', 'PNG'), ('mpeg-4', 'MP4')), default=0, verbose_name='Formats'),
        ),
        migrations.AlterField(
            model_name='deletedasset',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Image'),
        ),
    ]
